{{-  $pvcName := printf "%s-%s-%s" .Release.Name .Chart.Name "pvc" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName }}
  labels:
    app: {{ template "lzw.name" . }}
    chart: {{ template "lzw.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    env: management
    share: {{ .Values.storage.share }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
  selector:
    matchLabels:
      app: {{ template "lzw.name" . }}
      chart: {{ template "lzw.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      env: management
      share: {{ .Values.storage.share }}