apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-persistence-volume-graph
  labels: 
    storage: slow
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  storageClassName: my-farm-storage
  azureFile:
    secretName: static-persistence-secret
    shareName: graph
    readOnly: false