apiVersion: v1
kind: Secret
metadata:
  name: static-persistence-secret
type: Opaque
data:
  azurestorageaccountname: bXlmYXJtc3RvcmFnZQ==
  azurestorageaccountkey: SUkramVXWmZQUCtvTTBQTDhyb3dITkxUSU5GdWpUYUpSVFhrSjUxZENpS1kyQysvL2dXa21UaUphN1NvdmhrVHFJWW5VdGR3dE9jS1kyVEdlWjgrbnc9PQ==