apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-persistence-volume-registry
  labels: 
    env: production
    share: docker-registry
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  storageClassName: my-farm-storage
  azureFile:
    secretName: static-persistence-secret
    shareName: docker-registry
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-docker-registry
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-farm-storage
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      env: production
      share: docker-registry
---
