apiVersion: v1
kind: Secret
metadata:
  name: static-persistence-secret
type: Opaque
data:
  azurestorageaccountname: bXlmYXJtc3RvcmFnZQ==
  azurestorageaccountkey: SUkramVXWmZQUCtvTTBQTDhyb3dITkxUSU5GdWpUYUpSVFhrSjUxZENpS1kyQysvL2dXa21UaUphN1NvdmhrVHFJWW5VdGR3dE9jS1kyVEdlWjgrbnc9PQ==
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-farm-storage
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: myfarmstorage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-persistence-volume-graph
  labels: 
    env: staging
    share: graph
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  storageClassName: my-farm-storage
  azureFile:
    secretName: static-persistence-secret
    shareName: graph
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-farm-storage
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      env: staging
      share: graph
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-persistence-volume-pmo
  labels: 
    env: management
    share: pmo
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  storageClassName: my-farm-storage
  azureFile:
    secretName: static-persistence-secret
    shareName: pmo
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pmo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-farm-storage
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      env: management
      share: pmo